project:
  type: book

book:
  title: "<img src='img/logo_fjp.png' alt='Logo' style='vertical-align: middle; width:180px'> Vale do Jequitinhonha"
  subtitle: "Características Sociais dos Municípios com Potencial de Exploração do Lítio"
  # author:
    # - name: "[Caio Gonçalves](https://github.com/ccsgonc)"
    #   affiliation: Fundação João Pinheiro
    #   affiliation_url: https://fjp.mg.gov.br/
    # - name: "[Vitor Marinho](https://github.com/vitor-marinho-fjp)"
    #   affiliation: Fundação João Pinheiro
    #   affiliation_url: https://fjp.mg.gov.br/
  date: "05/21/2024"
  chapters:
    - index.qmd
    - autoridades.qmd
    - introducao.qmd
    - populacao.qmd
    - migracao.qmd
    - temp2.qmd
    - temp3.qmd
    - 2_Economia.qmd
    - 3_Social.qmd
    #- 7_fluxo_migratorio.qmd


    #- cad_unico.qmd
    - 3a_equipamentos_publicos.qmd
    - 5_Acoes.qmd
    - references.qmd
  sidebar:
    pinned: true
    
  search: 
    location: sidebar
    type: textbox
 
bibliography: 
    - references.bib

format:
  html:
    theme: Simplex
    mainfont: Arial
    base: /vale_litio/
  pdf:
    documentclass: scrreprt
lang: pt
editor: visual
